export enum DistributorProductLine {
  LOTUS = "lotus",
  LIMPOO = "limpoo",
}

export interface Distributor {
  id: number;
  name: string;
  address: string;
  phone: string;
  website?: string;
  state: string;
  latitude: number;
  longitude: number;
  zoom: number;
  distance?: number;
  country: string;
  product_line: Array<DistributorProductLine>;
}

export const DISTRIBUTORS_ITEMS: Array<Distributor> = [
  {
    id: 1,
    name: "QUICK CLEAN",
    address: "Av. Suplicy, 238 - Jd. Santa Mena - Guarulhos - SP",
    phone: "(11) 2414-4145",
    website: "https://www.quickclean.com.br/",
    state: "SP",
    latitude: -23.4505016,
    longitude: -46.5412414,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 2,
    name: "LOJA DO PROFISSIONAL",
    address: "Rua Guaicurus, 101 - Água Branca - São Paulo / SP",
    phone: "(11) 3863-7200",
    website: "https://www.lojadoprofissional.com.br/",
    state: "SP",
    latitude: -23.52348,
    longitude: -46.68671,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 3,
    name: "JATO SUPER",
    address:
      "Av. Feira De Santana, 71 – Jd. Vale do Sol - São José dos Campos / SP",
    phone: "(12) 3931-0594",
    website: "https://www.jatosuper.com.br/",
    state: "SP",
    latitude: -23.25721,
    longitude: -45.91123,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 4,
    name: "ARTWAX",
    address: "LOJA VIRTUAL",
    phone: "(11) 2339-3524 / (11) 98492-5351",
    website: "https://www.artwax.com.br/",
    state: "LOJA VIRTUAL",
    latitude: 0,
    longitude: 0,
    zoom: 7,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  // {
  //   id: 5,
  //   name: "PRISMA TECIDOS",
  //   phone: "(11) 4391-4800 / (11) 99191-9433",
  //   address: "Rua 24 de Fevereiro, 73 – Jardim Olavo Bilac, São Bernardo do Campo / SP",
  //   state: "SP",
  //   latitude: -23.70128,
  //   longitude: -46.556,
  //   zoom: 14,
  //   website: "https://www.prismatecidos.com.br/",
  //   country: "br",
  // },
  // {
  //   id: 6,
  //   name: "BURNOUT CA LTDA",
  //   phone: "(11) 94233-3524",
  //   address: "Alameda São Caetano, 960 - Jardim Santa Maria, Santo André / SP",
  //   state: "SP",
  //   latitude: -23.64728,
  //   longitude: -46.54712,
  //   zoom: 14,
  //   country: "br",
  // },
  {
    id: 7,
    name: "HIGIENIZA SUL",
    phone: "(51) 3276-6071",
    address: "Av. Salvador Leão, 137 - Sarandi, Porto Alegre / RS",
    state: "RS",
    latitude: -29.99606,
    longitude: -51.12897,
    zoom: 14,
    website: "https://higienizasul.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  // {
  //   id: 8,
  //   name: "HIG SERVICE",
  //   phone: "(48) 3050-5757",
  //   address: "Rod. João Gualberto Soares, 56 - Sala 06 - Ingleses Norte, Florianópolis / SC",
  //   state: "SC",
  //   latitude: -27.43983,
  //   longitude: -48.40251,
  //   zoom: 14,
  //   website: "https://www.higservicestore.com/",
  //   country: "br",
  // },
  {
    id: 9,
    name: "SHOWCAR",
    phone: "(48) 99147-9468",
    address: "R. Acre, 525 - Nossa Sra. da Salete, Criciúma / SC",
    state: "SC",
    latitude: -28.6845,
    longitude: -49.33872,
    zoom: 14,
    website: "https://showcar.net.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 10,
    name: "LOJA VERDE CAR",
    phone: "(48) 99166-1521",
    address: "Av. Brg. da Silva Paes, 02 - Campinas, São José / SC",
    state: "SC",
    latitude: -28.6845,
    longitude: -49.33872,
    zoom: 14,
    product_line: [DistributorProductLine.LOTUS],
    country: "br",
  },
  // {
  //   id: 11,
  //   name: "SEMPRE LIMPO",
  //   phone: "(47) 99775-0527",
  //   address: "Av. Brg. Da Silva Paes, 02 - Campinas, São José / SC",
  //   state: "SC",
  //   latitude: -27.59783,
  //   longitude: -48.60749,
  //   zoom: 14,
  //   website: "https://www.instagram.com/smplimpo/",
  //   country: "br",
  // },
  {
    id: 12,
    name: "CAR X PART’S",
    phone: "(41) 3779-7979",
    address: "Rua 24 de Maio, 1975 - Rebouças, Curitiba / PR",
    state: "PR",
    latitude: -25.45342,
    longitude: -49.26613,
    zoom: 14,
    website: "https://www.instagram.com/carxparts/",
    product_line: [DistributorProductLine.LOTUS],
    country: "br",
  },
  {
    id: 13,
    name: "LOJA LIMPSHOP",
    phone: "(21) 98087-0131",
    address: "JACAREPAGUÁ/RJ",
    state: "RJ",
    latitude: 0,
    longitude: 0,
    zoom: 14,
    website: "https://www.limpshop.com/",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    country: "br",
  },
  {
    id: 14,
    name: "EMPORIO CLEAN",
    phone: "(21) 98958-8258",
    address: "Alameda São Boaventura, 1190 - Fonseca, Niterói / RJ",
    state: "RJ",
    latitude: -22.88126,
    longitude: -43.0904,
    zoom: 14,
    website: "https://www.emporioclean.com.br/",
    product_line: [DistributorProductLine.LOTUS],
    country: "br",
  },
  {
    id: 15,
    name: "SB RIO",
    phone: "(21) 2424-5696",
    address:
      "Estr. do Gabinal, 1521 - Freguesia de Jacarepaguá, Rio de Janeiro / RJ",
    state: "RJ",
    latitude: -22.95203,
    longitude: -43.35057,
    zoom: 14,
    website: "https://www.sbrio.com/",
    product_line: [DistributorProductLine.LOTUS],
    country: "br",
  },
  {
    id: 16,
    name: "LOJA HIDRORIO Unidade I",
    phone: "(21) 2415-0666",
    address: "Estrada da Caroba, 1055 - Campo Grande, Rio de Janeiro / RJ",
    state: "RJ",
    latitude: -22.89725,
    longitude: -43.55782,
    zoom: 14,
    website: "",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 17,
    name: "LOJA HIDRORIO Unidade II",
    phone: "(21) 98346-5145",
    address:
      "Rua Professora Luiza Nogueira Gonçalves, 350 - Lj 109 - Recreio Dos Bandeirantes, Rio De Janeiro / RJ",
    state: "RJ",
    latitude: -23.00587,
    longitude: -43.44075,
    zoom: 14,
    website: "",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 18,
    name: "POLIBOX",
    phone: "(21) 2580-7544 / (21) 99632-7544",
    address:
      "CADEG Mercado Municipal do, R. Cap. Félix, 110 - 7 e 9 - Benfica, Rio de Janeiro / RJ",
    state: "RJ",
    latitude: -22.89459,
    longitude: -43.23656,
    zoom: 14,
    website: "https://www.polibox.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 19,
    name: "CENTER CLEAN",
    phone: "(21) 3888-4139",
    address: "R. Braga, 18 - Penha Circular, Rio de Janeiro / RJ",
    state: "RJ",
    latitude: -22.8315,
    longitude: -43.27932,
    zoom: 14,
    website: "https://www.centercleanbrasil.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  // {
  //   id: 20,
  //   name: "CENTER POA",
  //   phone: "(22) 99268-8678",
  //   address: "Av. Joaquim Nogueira, 430 - São Cristóvão, Cabo Frio / RJ",
  //   state: "RJ",
  //   latitude: -22.89134,
  //   longitude: -42.03588,
  //   zoom: 14,
  //   website: "https://www.facebook.com/centerpoahigienizacao/",
  //   country: "br",
  // },
  {
    id: 21,
    name: "RETOQUE TINTAS",
    phone: "(22) 2653-5374",
    address: "Rod. Amaral Peixoto, n° 144 - KM 71 - Bacaxá, Saquarema / RJ",
    state: "RJ",
    latitude: -22.88851,
    longitude: -42.46728,
    zoom: 14,
    website: "https://instagram.com/retoquetintas",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  // {
  //   id: 22,
  //   name: "GBCLEAN PRODUTOS",
  //   phone: "(24) 993243810",
  //   address: "R. Luís Ferreira Pinto, 99 - Loja 22 - Manejo, Resende / RJ",
  //   state: "RJ",
  //   latitude: -22.46878,
  //   longitude: -44.45508,
  //   zoom: 14,
  //   website: "http://instagram.com/gbclean_produtos",
  //   country: "br",
  // },
  {
    id: 23,
    name: "MAQ CLEAN",
    phone: "(27) 2141-8041",
    address: "Av. América, 487 - Jardim América, Cariacica / ES",
    state: "ES",
    latitude: -20.35225,
    longitude: -40.3657,
    zoom: 14,
    website: "https://www.maqclean.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 24,
    name: "SPECIALE CLEAN",
    phone: "(31) 97309-2373",
    address: "Av. Jair Rodrigues Vale, 230a - Inconfidentes, Contagem / MG",
    state: "MG",
    latitude: -19.95318,
    longitude: -44.03852,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 25,
    name: "DISTRIBUIDORA GATTI",
    phone: "(34) 99979-7859",
    address: "Av. Amazonas, 643 - Brasil, Uberlândia / MG",
    state: "MG",
    latitude: -18.89276,
    longitude: -48.26569,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 26,
    name: "UNIÃO W1 W2",
    phone: "(31) 99422-8985",
    address: "Av. Geraldo Inácio, 482 - Melo Viana, Cel. Fabriciano / MG",
    state: "MG",
    latitude: -19.50239,
    longitude: -42.63044,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 27,
    name: "HIGIENICAR",
    phone: "(31) 98817-0384",
    address: "R. Wenceslau Braz, 32 - Centro, Mariana / MG",
    state: "MG",
    latitude: -20.37541,
    longitude: -43.41756,
    zoom: 14,
    website: "https://instagram.com/higienecars",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 28,
    name: "EVOLUÇÃO CLEANING",
    phone: "(71) 99294-3418",
    address: "R. Buritirama - Recreio Ipitanga, Lauro de Freitas / BA",
    state: "BA",
    latitude: -12.88879,
    longitude: -38.3351,
    zoom: 14,
    website: "https://www.instagram.com/evolucao_cleaning/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 29,
    name: "3S HIGIENIZAÇÕES",
    phone: "(75) 99946-5661",
    address: "Ribeira do Pombal / BA",
    state: "BA",
    latitude: -10.83619,
    longitude: -38.54356,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 30,
    name: "HIGED PRODUTOS",
    phone: "(‪71) 98302‑2048‬",
    address: "Tv. Domingos Silva, 9 - Itapuã, Salvador / BA",
    state: "BA",
    latitude: -12.93471,
    longitude: -38.3628,
    zoom: 14,
    website: "https://www.instagram.com/higedprodutos/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  // {
  //   id: 31,
  //   name: "Paulista Lava rápido e Estacionamento",
  //   phone: "(79) 99660-0582‬",
  //   address: "Rua Acre, 2076 - América, Aracaju / SE",
  //   state: "SE",
  //   latitude: -10.923637,
  //   longitude: -37.076237,
  //   zoom: 14,
  //   country: "br",
  // },
  // {
  //   id: 32,
  //   name: "PRISMA ECO CLEAN",
  //   phone: "(81) 98322-9301‬",
  //   address: "Av. São Paulo, 797 - Jardim São Paulo, Recife / PE",
  //   state: "PE",
  //   latitude: -8.07895,
  //   longitude: -34.9414,
  //   zoom: 14,
  //   country: "br",
  //   product_line: DistributorProductLine.LOTUS,
  // },
  {
    id: 33,
    name: "JM IMPER",
    phone: "(87) 99189-6027‬",
    address: "R. 44 - São Goncalo, Petrolina / PE",
    state: "PE",
    latitude: -9.38528,
    longitude: -40.54943,
    zoom: 14,
    website: "https://www.jmimper.com.br",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 34,
    name: "LOJA AUTOCARE",
    phone: "(81) 99414-3313‬",
    address: "Av. Eng. Domingos Ferreira, 2784 - Boa Viagem, Recife / PE",
    state: "PE",
    latitude: -8.11373,
    longitude: -34.8946,
    zoom: 14,
    website: "https://www.lojaautocare.com.br",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 35,
    name: "LOJA ITP",
    phone: "(81) 97339-5358‬",
    address: "Estr. dos Remédios, 2226 - Loja 04 - Madalena, Recife / PE",
    state: "PE",
    latitude: -8.06018,
    longitude: -34.90713,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 36,
    name: "CLEAN PREMIERE",
    phone: "(61) 99560-9796‬",
    address: "St. A Norte QNA 14 Lote 04 - Taguatinga, Brasília / DF",
    state: "DF",
    latitude: -15.828332,
    longitude: -48.05425,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 37,
    name: "LOJA DOURADO",
    phone: "(61) 99167-3675‬",
    address: "St. H Norte QNH 11 lote 63 loja 4 - Taguatinga, Brasília / DF",
    state: "DF",
    latitude: -15.804988,
    longitude: -48.084135,
    zoom: 14,
    website: "https://www.lojadourado.com.br",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 38,
    name: "PROGIMAQ",
    phone: "(86) 99984-5560‬",
    address: "R. Alberto Leal Nunes, 2087 - Lourival Parente, Teresina / PI",
    state: "PI",
    latitude: -5.132925,
    longitude: -42.784933,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 39,
    name: "AUTHICA STILO",
    phone: "(86) 3235-8276‬",
    address: "Av. João XXIII, 2640 - Noivos, Teresina / PI",
    state: "PI",
    latitude: -5.081663,
    longitude: -42.774912,
    zoom: 14,
    website: "https://www.authica.com.br",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  // {
  //   id: 40,
  //   name: "BC AUTOS",
  //   phone: "(86) 99418-4635‬",
  //   address: "Av. Miguel Rosa, 1430 - Centro (Norte), Teresina / PI",
  //   state: "PI",
  //   latitude: -5.08086,
  //   longitude: -42.81705,
  //   zoom: 14,
  //   country: "br",
  // },
  // {
  //   id: 41,
  //   name: "ZR PRO",
  //   phone: "(86) 99912-2360‬",
  //   address: "R. Antônio Neves de Melo, 4985 - 4 - Parque Ideal, Teresina / PI",
  //   state: "PI",
  //   latitude: -5.0971,
  //   longitude: -42.7488,
  //   zoom: 14,
  //   website: "https://www.lojadourado.com.br",
  //   country: "br",
  //   product_line: [DistributorProductLine.LOTUS],
  // },
  {
    id: 43,
    name: "ACQUA LIMP",
    phone: "(99) 3524-6983",
    address: "R. Pernambuco, 1278 - Mercadinho, Imperatriz - MA",
    state: "MA",
    latitude: -5.52842,
    longitude: -47.47378,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 44,
    name: "FULL POLISH/NORTFIX",
    phone: "(91) 3227-4869",
    address: "Tv. de Breves, 486 - Cidade Velha, Belém / PA",
    state: "PA",
    latitude: -1.46568,
    longitude: -48.50087,
    zoom: 14,
    website: "https://www.nortfix.com.br",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 45,
    name: "ESPAÇO CLEAN",
    phone: "(96) 98131-4456",
    address:
      "D ao Lado do MPF - Av. Ernestino Borges, 525 - Julião Ramos, Macapá / AP",
    state: "AP",
    latitude: 0.04382,
    longitude: -51.06833,
    zoom: 14,
    website: "https://linktr.ee/espacocleanap",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 46,
    name: "BORA HIGIENIZAR O MUNDO",
    phone: "+351 934677486",
    address: "LOJA VIRTUAL",
    state: "LX",
    latitude: 38.70701,
    longitude: -9.13564,
    zoom: 14,
    website: "https://loja.borahigienizaromundo.com/",
    country: "pt",
    product_line: [DistributorProductLine.LOTUS],
  },
  // {
  //   id: 47,
  //   name: "NEW CLEAN",
  //   phone: "(11) 94085-7408",
  //   address:
  //     "Rua Aparecida - R. Aparecido Eusébio De Souza, 6 - Parque Jandaia, Carapicuíba - SP",
  //   state: "SP",
  //   latitude: -23.55428,
  //   longitude: -46.82407,
  //   zoom: 14,
  //   website: "https://newclean.jareservei.com/",
  //   country: "br",
  //   product_line: [DistributorProductLine.LOTUS],
  // },
  {
    id: 48,
    name: "SHOP RG CAR",
    phone: "(43) 3029-0300",
    address:
      "Av. Arcebispo Dom Geraldo Fernandes, 2777 - Loja 01 - Centro, Londrina - PR",
    state: "PR",
    latitude: -23.30136,
    longitude: -51.16966,
    zoom: 14,
    website: "https://www.shoprgcar.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 49,
    name: "CS DISTRIBUIDORA",
    phone: "(84) 98153-6899",
    address:
      "Rua Lídia Ferreira De Souza, 09CS-C - Nova Esperança - Parnamirim - RN",
    state: "RN",
    latitude: -5.93614,
    longitude: -35.27701,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 50,
    name: "KUCHAR",
    phone: "(11) 5523-6364",
    address: "Av. Washington Luís, 714 - Santo Amaro, São Paulo - SP",
    state: "SP",
    latitude: -23.66035,
    longitude: -46.70345,
    zoom: 14,
    country: "br",
    website: "https://www.kuchar.com.br/",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  // {
  //   id: 51,
  //   name: "NEW CLEAN",
  //   phone: "(11) 94085-7408",
  //   address: "R. José Soares de Andrade, 144 - Parque Jandaia, Carapicuíba - SP",
  //   state: "SP",
  //   latitude: -23.5545,
  //   longitude: -46.82269,
  //   zoom: 14,
  //   country: "br",
  //   website: "https://newclean.jareservei.com/",
  // },
  {
    id: 52,
    name: "ALLAN PRODUTOS AUTOMOTIVOS",
    phone: "(64) 98133-3564",
    address: "Rua 18, 1341, Qd. 67 Lt. 7B - Bairro Popular - Rio Verde - GO",
    state: "GO",
    latitude: -17.79713,
    longitude: -50.92367,
    zoom: 14,
    country: "br",
    website: "",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  // {
  //   id: 53,
  //   name: "ITALIANI DISTRIBUIDORA",
  //   phone: "(47) 3271-1716",
  //   address: "R. Anita Garibaldi, 1381 - 04 - Anita Garibaldi, Joinville - SC",
  //   state: "SC",
  //   latitude: -26.32414,
  //   longitude: -48.85523,
  //   zoom: 14,
  //   country: "br",
  //   website: "https://italianidistribuidora.com.br/",
  //   product_line: [DistributorProductLine.LOTUS],
  // },
  {
    id: 54,
    name: "VM AUTOCLEAN",
    phone: "(11) 94232-0372",
    address: "Av. Dos Latinos, 647 B, Jardim Santa Terezinha, São Paulo - SP",
    state: "SP",
    latitude: -23.57292,
    longitude: -46.4981,
    zoom: 14,
    country: "br",
    website: "https://www.vmautoclean.com.br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 55,
    name: "MULTI SOLUÇÕES",
    phone: "(51) 99696-6446",
    address: "R. José Inácio da Cunha, 5 - Sarandi, Porto Alegre - RS",
    state: "RS",
    latitude: -29.99525,
    longitude: -51.13127,
    zoom: 14,
    country: "br",
    website: "https://www.multisolucoesltda.com.br/",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 56,
    name: "CASA DO LAVA-CAR",
    phone: "(43) 3024-6672",
    address: "R. Guaporé, 500 - Centro, Londrina - PR",
    state: "PR",
    latitude: -23.3044,
    longitude: -51.16367,
    zoom: 14,
    country: "br",
    website: "https://www.instagram.com/casa_do_lava_car/",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 57,
    name: "DOUTOR TAPETE",
    phone: "(19) 99921-9324",
    address:
      "R. Gen. Góes Monteiro, 476 - Jardim Elite, Piracicaba - SP, 13417-381",
    state: "SP",
    latitude: -22.73824,
    longitude: -47.6389,
    zoom: 14,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 58,
    name: "LAVACAR CUIABÁ",
    phone: "(65) 99909-1824",
    address:
      "Rua Fernando Correa da Costa, 707 - Bairro Areão, Cuiabá - MT, 78010-400",
    state: "MT",
    latitude: -15.61688,
    longitude: -56.05281,
    zoom: 14,
    country: "br",
    website: "",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 59,
    name: "LAVACAR RONDONÓPOLIS",
    phone: "(66) 99675-8040",
    address:
      "Rua Fernando Correa Da Costa, 870 - Centro - Rondonopolis - MT, 78700-100",
    state: "MT",
    latitude: -16.46875,
    longitude: -54.63493,
    zoom: 14,
    country: "br",
    website: "",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 60,
    name: "JRCLEAN HIGIENIZAÇÕES",
    phone: "(11) 94725-3479",
    address:
      "Rua Angela Zampol N 234 - Bairro Suissa - Ribeirão Pires - SP, 09424-270",
    state: "SP",
    latitude: -23.714672,
    longitude: -46.422486,
    zoom: 14,
    country: "br",
    website: "https://www.jrcleanhigienizacoes.com",
    product_line: [DistributorProductLine.LOTUS],
  },

  {
    id: 61,
    name: "ESTÚDIO VIP",
    phone: "(83) 98894-2569",
    address:
      "Av. Barão de Mamanguape, 25. Loja 4 - Torre - João Pessoa, Brazil 58040-330",
    state: "PB",
    latitude: -7.12013,
    longitude: -34.86175,
    zoom: 14,
    country: "br",
    website: "https://www.instagram.com/lojaestudiovip/",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 62,
    name: "D'ARTIBALE DECOR",
    phone: "(19) 3461-6314",
    address: "R. São Marcos, 39 - São Manoel, Americana - SP, 13472-200",
    state: "SP",
    latitude: -22.72831,
    longitude: -47.31455,
    zoom: 14,
    country: "br",
    website: "https://dartibaledecor.com.br/",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 63,
    name: "HARU MARKET",
    address: "LOJA VIRTUAL",
    phone: "",
    website: "https://www.mercadolivre.com.br/pagina/harumarket",
    state: "LOJA VIRTUAL",
    latitude: 0,
    longitude: 0,
    zoom: 7,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 64,
    name: "HIGIPLACE",
    address: "LOJA VIRTUAL",
    phone: "(11) 95442-0018",
    website: "https://www.mercadolivre.com.br/pagina/higiplace",
    state: "LOJA VIRTUAL",
    latitude: 0,
    longitude: 0,
    zoom: 7,
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 65,
    name: "CASA DO IMPERMEABILIZADOR",
    phone: "",
    address:
      "Rua 22-E Qd 135 Lt 30 SL 01 - Garavelo Residencial Park - Aparecida De Goiania - GO - 74932-410",
    state: "GO",
    latitude: -16.75795,
    longitude: -49.33754,
    zoom: 14,
    country: "br",
    website: "https://www.instagram.com/casadoimpermeabilizador/",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 66,
    name: "SEMPRE LIMPO",
    phone: "(47) 97750527",
    address: "R. José Roberto Otto, 766, Porto Belo - SC, 88210-000",
    state: "SC",
    latitude: -27.15204,
    longitude: -48.58761,
    zoom: 14,
    country: "br",
    website: "https://www.instagram.com/smplimpo",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 68,
    name: "LOJA DO HIGIENIZADOR",
    phone: "(98) 985700926",
    address:
      "R. Inácio Xavier de Carvalho, 586 - São Francisco, São Luís - MA, 65076-360",
    state: "MA",
    latitude: -2.53468,
    longitude: -44.26947,
    zoom: 14,
    country: "br",
    website: "https://www.instagram.com/lojadohigienizador/",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 69,
    name: "STL / PRODUTOS DE LIMPEZA",
    phone: "(11) 26598026",
    address:
      "Av. Min. Laudo Ferreira de Camargo, 327 - Jardim Peri Peri, São Paulo - SP, 05537-001",
    state: "SP",
    latitude: -23.58696,
    longitude: -46.73708,
    zoom: 14,
    country: "br",
    website: "https://stldistribuidora.lojaintegrada.com.br/",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 70,
    name: "GT CAR CARE",
    phone: "(62) 41015992",
    address:
      "Av T7 Qd 43 Lote 01 Sala 01 número 1165 - Bairro Setor Bueno Goiânia - GO, 74215-030",
    state: "GO",
    latitude: -16.691193,
    longitude: -49.282061,
    zoom: 14,
    country: "br",
    website: "https://www.instagram.com/gtcarcare_/",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 71,
    name: "BADRAN QUIMICA",
    phone: "(17) 996616060",
    address: "LOJA VIRTUAL",
    state: "SP",
    latitude: 0,
    longitude: 0,
    zoom: 14,
    website: "https://www.instagram.com/badranquimica/",
    country: "br",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 72,
    name: "LEG SOLUÇÕES TIMON",
    phone: "(99) 98223-6772",
    address: "Av. Teresina, 520 - Parque Piaui, Timon - MA, 65631-205",
    state: "MA",
    latitude: -5.09254,
    longitude: -42.83298,
    zoom: 14,
    website: "https://www.instagram.com/legsolucoes/",
    country: "br",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 73,
    name: "LEG SOLUÇÕES TERESINA",
    phone: "(86) 98888-5836",
    address:
      "Av. Nossa Sra. de Fátima, 2451 - Fátima, Teresina - PI, 64049-528",
    state: "PI",
    latitude: -5.06609,
    longitude: -42.7936,
    zoom: 14,
    website: "https://www.instagram.com/legsolucoes/",
    country: "br",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 74,
    name: "M&M PRODUTOS DE LIMPEZA",
    phone: "(48) 99671-5768",
    address:
      "Av. Renato Ramos da Silva, 2781 - Vila Santo Antonio, Imbituba - SC, 88780-000",
    state: "SC",
    latitude: -28.26114,
    longitude: -48.68899,
    zoom: 14,
    website: "https://www.instagram.com/mmimbprodutosdelimpeza/",
    country: "br",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 75,
    name: "IMPÉRIO DAS UTILIDADES",
    phone: "(47) 99199-9253",
    address: "R. Gen. Osório, 1920 - Velha, Blumenau - SC, 89041-604",
    state: "SC",
    latitude: -26.91146,
    longitude: -49.1132,
    zoom: 14,
    website: "https://www.instagram.com/imperio.dasutilidades/",
    country: "br",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 76,
    name: "LIMPEJA PRODUTOS",
    phone: "(11) 99230-6966",
    address: "LOJA VIRTUAL",
    state: "SP",
    latitude: 0,
    longitude: 0,
    zoom: 14,
    website: "https://www.limpejaprodutos.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LIMPOO],
  },
  {
    id: 77,
    name: "ZAPLUSCAR VILA VILHA",
    phone: "(11) 99230-6966",
    address:
      "Av. Leila Diniz, 711, lojas 05,06,07 e 08 - Ilha dos Bentos, Vila Velha - ES",
    state: "ES",
    latitude: -20.3721305,
    longitude: -40.3191009,
    zoom: 14,
    website: "https://www.instagram.com/zapluscarvilavelha/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 78,
    name: "DL DISTRILIMP",
    phone: "(27) 99929-0298",
    address:
      "Av. Pref. Anário Marreiro, 92 - Nossa Sra. da Conceição, Linhares - ES",
    state: "ES",
    latitude: -19.379646,
    longitude: -40.067748,
    zoom: 14,
    website: "https://distrilimp.nextgocard.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 79,
    name: "CLEAN HOUSE",
    phone: "(86) 9982-5609",
    address: "Av. Homero Castelo Branco, 259 - l04 - Jóquei, Teresina - PI",
    state: "PI",
    latitude: -5.079382,
    longitude: -42.780806,
    zoom: 14,
    website: "https://www.instagram.com/cleanhouseteresina/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 80,
    name: "BARAK PRODUTOS AUTOMOTIVOS",
    phone: "(31) 97231-0749",
    address: "R. Codó, 33 - Filadélfia, Betim - MG",
    state: "MG",
    latitude: -19.966143,
    longitude: -44.183337,
    zoom: 14,
    website: "https://lojabarak.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 81,
    name: "PROVALE AUTO CARE",
    phone: "(12) 3018-1700",
    address:
      "Av. Andrômeda, 3540 - Bosque dos Eucaliptos, São José dos Campos - SP",
    state: "SP",
    latitude: -23.243594,
    longitude: -45.885466,
    zoom: 14,
    website: "https://provale.net.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 82,
    name: "Galdez Lubrificantes e Esteticar - Loja 01",
    phone: "(98) 97024-7388",
    address: "Av. Kennedy, 173 - Coreia, São Luís - MA",
    state: "MA",
    latitude: -2.540919,
    longitude: -44.286638,
    zoom: 14,
    website: "https://www.instagram.com/galdez_lubrificantes/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 83,
    name: "Galdez Lubrificantes e Esteticar - Loja 02",
    phone: "(98) 97024-7388",
    address: "R. da Assembléia, 25 - Vila Vicente Fialho, São Luís - MA",
    state: "MA",
    latitude: -2.508539,
    longitude: -44.240149,
    zoom: 14,
    website: "https://www.instagram.com/galdez_lubrificantes/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 84,
    name: "CASTORES PRODUTOS AUTOMOTIVOS",
    phone: "(11) 2598-8822",
    address:
      "Av senador Vergueiro, 3176 bairro Anchieta - São Bernardo do campo - SP",
    state: "SP",
    latitude: -23.6677741,
    longitude: -46.5628672,
    zoom: 14,
    website: "https://www.castores.com.br",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 85,
    name: "MENDES AUTO",
    phone: "(18)3907-7973",
    address:
      "Av Juscelino Kubitscheck de Oliveira, 2309 - Jardim everest - Presidente Prudente - SP",
    state: "SP",
    latitude: -22.105361,
    longitude: -51.4357949,
    zoom: 14,
    website: "https://www.mendesauto.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
  {
    id: 86,
    name: "Native Comércio",
    phone: "(81)9110-1063",
    address:
      "Av. Adjar da Silva Casé, 168 - Loja 1 - Indianópolis, Caruaru - PE",
    state: "PE",
    latitude: -8.2926978,
    longitude: -35.9580692,
    zoom: 14,
    website: "https://www.nativecomercio.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 87,
    name: "DEPRIMEIRA PRODUTOS",
    phone: "(85)9140-5337",
    address: " R. Anselmo Nogueira, 50 (Loja 05) - Bonsucesso - Fortaleza - CE",
    state: "CE",
    latitude: -3.779152,
    longitude: -38.5869066,
    zoom: 14,
    website: "",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 88,
    name: "Casa do Lavador UN. Gravataí",
    phone: "(51)3128-0500",
    address:
      " Av. Dorival Cândido Luz de Oliveira, 6735 - Bom Princípio, Gravataí - RS",
    state: "RS",
    latitude: -29.9321103,
    longitude: -51.0645935,
    zoom: 14,
    website: "https://www.casadolavador.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 89,
    name: "Casa do Lavador UN. Porto Alegre I",
    phone: "(51)3207-8541",
    address: "Rua Cerro Azul, 646 - Santa Maria Goretti, Porto Alegre - RS",
    state: "RS",
    latitude: -30.0046797,
    longitude: -51.180852,
    zoom: 14,
    website: "https://www.casadolavador.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 90,
    name: "Casa do Lavador UN. Porto Alegre II",
    phone: "(51)3737-4300",
    address:
      " Av. Bento Gonçalves, 8781 - loja 10 - São José, Porto Alegre - RS",
    state: "RS",
    latitude: -30.0767603,
    longitude: -51.133106,
    zoom: 14,
    website: "https://www.casadolavador.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 91,
    name: "Casa do Lavador UN. Porto Alegre III",
    phone: "(51)99763-5649",
    address: "Av. Edgar Píres de Castro, 503 - Hípica, Porto Alegre - RS",
    state: "RS",
    latitude: -30.1565874,
    longitude: -51.1882189,
    zoom: 14,
    website: "https://www.casadolavador.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 92,
    name: "Casa do Lavador UN. Osório",
    phone: "(51)99887-1744",
    address: " R. Costa Gama, 915 - Centro, Osório - RS",
    state: "RS",
    latitude: -29.8944676,
    longitude: -50.268441,
    zoom: 14,
    website: "https://www.casadolavador.com.br/",
    country: "br",
    product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
  },
  {
    id: 93,
    name: "Loja Super Brilho",
    phone: "(79)99681-6592",
    address: " Rua Acre, 819 - Siqueira CamposAracaju - SE",
    state: "SE",
    latitude: -10.9113614,
    longitude: -37.073372,
    zoom: 14,
    website: "",
    country: "br",
    product_line: [DistributorProductLine.LOTUS],
  },
];
