export enum DistributorProductLine {
  LOTUS = "lotus",
  LIMPOO = "limpoo",
}

export interface Distributor {
  id: number;
  name: string;
  address: string;
  phone: string;
  website?: string;
  state: string;
  latitude: number;
  longitude: number;
  zoom: number;
  distance?: number;
  country: string;
  product_line: Array<DistributorProductLine>;
}

export type DistributorInput = Omit<Distributor, "id">;

const DISTRIBUTORS_BY_STATE: Record<string, Array<DistributorInput>> = {
  "BA": [
    {
      name: "HIGED PRODUTOS",
      phone: "(71) 98302‑2048",
      address: "Tv. Domingos Silva, 9 - Itapuã, Salvador / BA",
      state: "BA",
      latitude: -12.93471,
      longitude: -38.3628,
      zoom: 14,
      website: "https://www.instagram.com/higedprodutos/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
  ],
  "CE": [
    {
      name: "DEPRIMEIRA PRODUTOS",
      phone: "(85)9140-5337",
      address: " R. Anselmo Nogueira, 50 (Loja 05) - Bonsucesso - Fortaleza - CE",
      state: "CE",
      latitude: -3.779152,
      longitude: -38.5869066,
      zoom: 14,
      website: "",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
  ],
  "DF": [
    {
      name: "CLEAN PREMIERE",
      phone: "(61) 99560-9796",
      address: "St. A Norte QNA 14 Lote 04 - Taguatinga, Brasília / DF",
      state: "DF",
      latitude: -15.828332,
      longitude: -48.05425,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "LOJA DOURADO",
      phone: "(61) 99167-3675",
      address: "St. H Norte QNH 11 lote 63 loja 4 - Taguatinga, Brasília / DF",
      state: "DF",
      latitude: -15.804988,
      longitude: -48.084135,
      zoom: 14,
      website: "https://www.lojadourado.com.br",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "ES": [
    {
      name: "DL DISTRILIMP",
      phone: "(27) 99929-0298",
      address:
        "Av. Pref. Anário Marreiro, 92 - Nossa Sra. da Conceição, Linhares - ES",
      state: "ES",
      latitude: -19.379646,
      longitude: -40.067748,
      zoom: 14,
      website: "https://distrilimp.nextgocard.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "MAQ CLEAN",
      phone: "(27) 2141-8041",
      address: "Av. América, 487 - Jardim América, Cariacica / ES",
      state: "ES",
      latitude: -20.35225,
      longitude: -40.3657,
      zoom: 14,
      website: "https://www.maqclean.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "ZAPLUSCAR VILA VILHA",
      phone: "(11) 99230-6966",
      address:
        "Av. Leila Diniz, 711, lojas 05,06,07 e 08 - Ilha dos Bentos, Vila Velha - ES",
      state: "ES",
      latitude: -20.3721305,
      longitude: -40.3191009,
      zoom: 14,
      website: "https://www.instagram.com/zapluscarvilavelha/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "GO": [
    {
      name: "A CIÊNCIA DA LIMPEZA",
      phone: "(61) 99392-1510",
      address: "R. 12, Quadra 36 lote 10 loja B e C - Morada Nobre, Valparaíso de Goiás - GO, 72870-369",
      state: "GO",
      latitude: -16.0658,
      longitude: -47.9756,
      zoom: 14,
      website: "https://www.instagram.com/acienciadalimpezavalparaiso/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "ALLAN PRODUTOS AUTOMOTIVOS",
      phone: "(64) 98133-3564",
      address: "Rua 18, 1341, Qd. 67 Lt. 7B - Bairro Popular - Rio Verde - GO",
      state: "GO",
      latitude: -17.79713,
      longitude: -50.92367,
      zoom: 14,
      country: "br",
      website: "",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "GT CAR CARE",
      phone: "(62) 41015992",
      address:
        "Av T7 Qd 43 Lote 01 Sala 01 número 1165 - Bairro Setor Bueno Goiânia - GO, 74215-030",
      state: "GO",
      latitude: -16.691193,
      longitude: -49.282061,
      zoom: 14,
      country: "br",
      website: "https://www.instagram.com/gtcarcare_/",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "LOJA VIRTUAL": [
    {
      name: "HARU MARKET",
      address: "LOJA VIRTUAL",
      phone: "",
      website: "https://www.mercadolivre.com.br/pagina/harumarket",
      state: "LOJA VIRTUAL",
      latitude: 0,
      longitude: 0,
      zoom: 7,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "HIGIPLACE",
      address: "LOJA VIRTUAL",
      phone: "(11) 95442-0018",
      website: "https://www.mercadolivre.com.br/pagina/higiplace",
      state: "LOJA VIRTUAL",
      latitude: 0,
      longitude: 0,
      zoom: 7,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "LX": [
    {
      name: "BORA HIGIENIZAR O MUNDO",
      phone: "+351 934677486",
      address: "LOJA VIRTUAL",
      state: "LX",
      latitude: 38.70701,
      longitude: -9.13564,
      zoom: 14,
      website: "https://loja.borahigienizaromundo.com/",
      country: "pt",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "MA": [
    {
      name: "Galdez Lubrificantes e Esteticar - Loja 01",
      phone: "(98) 97024-7388",
      address: "Av. Kennedy, 173 - Coreia, São Luís - MA",
      state: "MA",
      latitude: -2.540919,
      longitude: -44.286638,
      zoom: 14,
      website: "https://www.instagram.com/galdez_lubrificantes/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "Galdez Lubrificantes e Esteticar - Loja 02",
      phone: "(98) 97024-7388",
      address: "R. da Assembléia, 25 - Vila Vicente Fialho, São Luís - MA",
      state: "MA",
      latitude: -2.508539,
      longitude: -44.240149,
      zoom: 14,
      website: "https://www.instagram.com/galdez_lubrificantes/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "MG": [
    {
      name: "AUTO CORES",
      phone: "(31)98707-1002",
      address: "Av. Presidente Carlos Luz, 45 - Caiçaras, Belo Horizonte - MG, 31230-010",
      state: "MG",
      latitude: -19.9080226,
      longitude: -43.9629912,
      zoom: 14,
      website: "https://www.lojaautocores.com/loja/busca.php?loja=706429&palavra_busca=L%D3TUS",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "DISTRIBUIDORA GATTI",
      phone: "(34) 99979-7859",
      address: "Av. Amazonas, 643 - Brasil, Uberlândia / MG",
      state: "MG",
      latitude: -18.89276,
      longitude: -48.26569,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "J A SOLUÇÕES DE LIMPEZA",
      phone: "+55 32 9813-2642",
      address: "R. Hipólito Caron, 134 - Centro, Juiz de Fora - MG, 36013-130",
      state: "MG",
      latitude: -21.759,
      longitude: -43.351,
      zoom: 14,
      website: "https://www.instagram.com/jasolucoes.limp/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "MAIS BRILHO JF",
      phone: "(32) 98804-3046",
      address: "R. Teresa Cristina, 185 - Mariano Procópio, Juiz de Fora - MG, 36080-120",
      state: "MG",
      latitude: -21.744,
      longitude: -43.348,
      zoom: 14,
      website: "https://maisbrilhojf.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "RN PRODUTOS AUTOMOTIVOS",
      phone: "(34) 99716-3848",
      address: "R. Pref. Camundinho, 1003 - Brasil, Patos de Minas - MG, 38700-199",
      state: "MG",
      latitude: -18.5932,
      longitude: -46.5183,
      zoom: 14,
      website: "https://www.rnprodutosautomotivos.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "SPECIALE CLEAN",
      phone: "(31) 97309-2373",
      address: "Av. Jair Rodrigues Vale, 230a - Inconfidentes, Contagem / MG",
      state: "MG",
      latitude: -19.95318,
      longitude: -44.03852,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "UNIÃO W1 W2",
      phone: "(31) 99422-8985",
      address: "Av. Geraldo Inácio, 482 - Melo Viana, Cel. Fabriciano / MG",
      state: "MG",
      latitude: -19.50239,
      longitude: -42.63044,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "MS": [
    {
      name: "Maxxus Autoshop",
      phone: "(67)99856-1063",
      address: "Rua Bela Vista, 176, A - Jardim São Pedro, Dourados - MS, 79810-030",
      state: "MS",
      latitude: -22.2340544,
      longitude: -54.8116976,
      zoom: 14,
      website: "https://www.maxxusautoshop.com.br/?srsltid=AfmBOoqa46xHE1KNWjPAAXNkYlHaUetcg2Hmipi8dj7QzovDyEKvlUyL",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "POTENCIAL SOLUÇÕES",
      phone: "(67) 99849-1510",
      address: "R. Antônio Rahe, 403 - Mata do Jacinto, Campo Grande - MS, 79033-580",
      state: "MS",
      latitude: -20.4142,
      longitude: -54.5756,
      zoom: 14,
      website: "https://www.instagram.com/potencial_solucoes_limpeza/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "MT": [
    {
      name: "LAVACAR CUIABÁ",
      phone: "(65) 99909-1824",
      address:
        "Rua Fernando Correa da Costa, 707 - Bairro Areão, Cuiabá - MT, 78010-400",
      state: "MT",
      latitude: -15.61688,
      longitude: -56.05281,
      zoom: 14,
      country: "br",
      website: "",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "LAVACAR RONDONÓPOLIS",
      phone: "(66) 99675-8040",
      address:
        "Rua Fernando Correa Da Costa, 870 - Centro - Rondonopolis - MT, 78700-100",
      state: "MT",
      latitude: -16.46875,
      longitude: -54.63493,
      zoom: 14,
      country: "br",
      website: "",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "PA": [
    {
      name: "FULL POLISH/NORTFIX",
      phone: "(91) 3227-4869",
      address: "Tv. de Breves, 486 - Cidade Velha, Belém / PA",
      state: "PA",
      latitude: -1.46568,
      longitude: -48.50087,
      zoom: 14,
      website: "https://www.nortfix.com.br",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "PREMIUM CAR CENTER CANAÂ",
      phone: "(94)99223-5317",
      address: "Rua Araponema, S/N - Bela Vista - Canaã Dos Carajas - PA - 68354-267",
      state: "PA",
      latitude: -6.523731,
      longitude: -49.8632617,
      zoom: 14,
      website: "https://www.instagram.com/premium_car_shop/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "PREMIUM CAR CENTER CURIONOPOLIS",
      phone: "(94)99223-5317",
      address: "Av Maranhão, n° 167 - Curionopolis - PA - 68523-000",
      state: "PA",
      latitude: -6.1039061,
      longitude: -49.6008278,
      zoom: 14,
      website: "https://www.instagram.com/premium_car_shop/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "PREMIUM CAR CENTER PARAUAPEBAS",
      phone: "(94)99223-5317",
      address: "Avenida A, QD 306, Lote 03 - Cidade Jardim - Parauapebas - PA - 68515-000",
      state: "PA",
      latitude: -6.085318,
      longitude: -49.858822,
      zoom: 14,
      website: "https://www.instagram.com/premium_car_shop/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "PB": [
    {
      name: "ESTÚDIO VIP",
      phone: "(83) 98894-2569",
      address:
        "Av. Barão de Mamanguape, 25. Loja 4 - Torre - João Pessoa, Brazil 58040-330",
      state: "PB",
      latitude: -7.12013,
      longitude: -34.86175,
      zoom: 14,
      country: "br",
      website: "https://www.instagram.com/lojaestudiovip/",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "Prodetailer Loja 1",
      phone: "(83)98702-2819",
      address: "R. João Suassuna, 443 - Centro, Campina Grande - PB, 58400-036",
      state: "PB",
      latitude: -7.2156444,
      longitude: -35.8921284,
      zoom: 14,
      website: "https://lojaprodetailer.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "Prodetailer Loja 2",
      phone: "(83)98702-2819",
      address: "Av. Pres. Juscelino Kubitschek, 812 - Cruzeiro, Campina Grande - PB, 58415-530",
      state: "PB",
      latitude: -7.2446852,
      longitude: -35.9062564,
      zoom: 14,
      website: "https://lojaprodetailer.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "ZAPLUS CAR JOÃO PESSOA",
      phone: "(83) 99864-9696",
      address: "Av. Pres. Epitácio Pessoa, 667 - Lot. Eugenio Neiva, João Pessoa - PB, 58030-002",
      state: "PB",
      latitude: -7.119,
      longitude: -34.849,
      zoom: 14,
      website: "https://www.instagram.com/zapluscar.joaopessoa/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "PE": [
    {
      name: "LOJA AUTOCARE",
      phone: "(81) 99414-3313",
      address: "Av. Eng. Domingos Ferreira, 2784 - Boa Viagem, Recife / PE",
      state: "PE",
      latitude: -8.11373,
      longitude: -34.8946,
      zoom: 14,
      website: "https://www.lojaautocare.com.br",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "LOJA ITP",
      phone: "(81) 97339-5358",
      address: "Estr. dos Remédios, 2226 - Loja 04 - Madalena, Recife / PE",
      state: "PE",
      latitude: -8.06018,
      longitude: -34.90713,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "Native Comércio",
      phone: "(81)9110-1063",
      address:
        "Av. Adjar da Silva Casé, 168 - Loja 1 - Indianópolis, Caruaru - PE",
      state: "PE",
      latitude: -8.2926978,
      longitude: -35.9580692,
      zoom: 14,
      website: "https://www.nativecomercio.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
  ],
  "PI": [
    {
      name: "PICOS CLEAN",
      phone: "(89) 98132-5728",
      address: "Rua João Nunes, 73 - Canto da Varzea, Picos - PI, 64600-184",
      state: "PI",
      latitude: -7.077,
      longitude: -41.467,
      zoom: 14,
      website: "https://www.instagram.com/lufsolucoes?igsh=amRweWlhZDgyMXI4",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "PROGIMAQ",
      phone: "(86) 99984-5560",
      address: "R. Alberto Leal Nunes, 2087 - Lourival Parente, Teresina / PI",
      state: "PI",
      latitude: -5.132925,
      longitude: -42.784933,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "ZAPLUS CAR TERESINA",
      phone: "(86) 98103-7039",
      address: "Rua Oscar Gil Castelo Branco, 2645 - São Cristóvão, Teresina - PI, 64055-020",
      state: "PI",
      latitude: -5.0878,
      longitude: -42.7732,
      zoom: 14,
      website: "https://www.instagram.com/zapluscarteresina/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "PR": [
    {
      name: "ACS Automotive Care Solutions",
      phone: "(42)99161-2767",
      address: "R. Henrique Hennemberg, 393 - Boa Vista - Ponta Grossa - PR, 84070-490",
      state: "PR",
      latitude: -25.0792769,
      longitude: -50.1944275,
      zoom: 14,
      website: "",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "CAR X PART’S",
      phone: "(41) 3779-7979",
      address: "Rua 24 de Maio, 1975 - Rebouças, Curitiba / PR",
      state: "PR",
      latitude: -25.45342,
      longitude: -49.26613,
      zoom: 14,
      website: "https://www.instagram.com/carxparts/",
      product_line: [DistributorProductLine.LOTUS],
      country: "br",
    },
    {
      name: "CASA DO LAVA-CAR",
      phone: "(43) 3024-6672",
      address: "R. Guaporé, 500 - Centro, Londrina - PR",
      state: "PR",
      latitude: -23.3044,
      longitude: -51.16367,
      zoom: 14,
      country: "br",
      website: "https://www.instagram.com/casa_do_lava_car/",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "SHOP RG CAR",
      phone: "(43) 3029-0300",
      address:
        "Av. Arcebispo Dom Geraldo Fernandes, 2777 - Loja 01 - Centro, Londrina - PR",
      state: "PR",
      latitude: -23.30136,
      longitude: -51.16966,
      zoom: 14,
      website: "https://www.shoprgcar.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "RJ": [
    {
      name: "ALLTEC",
      phone: "(21) 96900-8849",
      address: "R. Lateral, 12940 - Jardim Tropical, Nova Iguaçu - RJ, 26010-660",
      state: "RJ",
      latitude: -22.747,
      longitude: -43.458,
      zoom: 14,
      website: "https://alltecprodutos.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "CENTER CLEAN",
      phone: "(21) 3888-4139",
      address: "R. Braga, 18 - Penha Circular, Rio de Janeiro / RJ",
      state: "RJ",
      latitude: -22.8315,
      longitude: -43.27932,
      zoom: 14,
      website: "https://www.centercleanbrasil.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "DETAIL PRO SHOP",
      phone: "(22)99914-3109",
      address: "R. Ten-Cel. Cardoso, 832 - loja 1 - Centro, Campos dos Goytacazes - RJ, 28035-044",
      state: "RJ",
      latitude: -21.7561245,
      longitude: -41.3340901,
      zoom: 14,
      website: "",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "EMPORIO CLEAN",
      phone: "(21) 98958-8258",
      address: "Alameda São Boaventura, 1190 - Fonseca, Niterói / RJ",
      state: "RJ",
      latitude: -22.88126,
      longitude: -43.0904,
      zoom: 14,
      website: "https://www.emporioclean.com.br/",
      product_line: [DistributorProductLine.LOTUS],
      country: "br",
    },
    {
      name: "LOJA HIDRORIO Unidade I",
      phone: "(21) 2415-0666",
      address: "Estrada da Caroba, 1055 - Campo Grande, Rio de Janeiro / RJ",
      state: "RJ",
      latitude: -22.89725,
      longitude: -43.55782,
      zoom: 14,
      website: "",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "LOJA HIDRORIO Unidade II",
      phone: "(21) 98346-5145",
      address:
        "Rua Professora Luiza Nogueira Gonçalves, 350 - Lj 109 - Recreio Dos Bandeirantes, Rio De Janeiro / RJ",
      state: "RJ",
      latitude: -23.00587,
      longitude: -43.44075,
      zoom: 14,
      website: "",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "LOJA LIMPSHOP",
      phone: "(21) 98087-0131",
      address: "JACAREPAGUÁ/RJ",
      state: "RJ",
      latitude: 0,
      longitude: 0,
      zoom: 14,
      website: "https://www.limpshop.com/",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
      country: "br",
    },
    {
      name: "POLIBOX",
      phone: "(21) 2580-7544 / (21) 99632-7544",
      address:
        "CADEG Mercado Municipal do, R. Cap. Félix, 110 - 7 e 9 - Benfica, Rio de Janeiro / RJ",
      state: "RJ",
      latitude: -22.89459,
      longitude: -43.23656,
      zoom: 14,
      website: "https://www.polibox.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "RETOQUE TINTAS",
      phone: "(22) 2653-5374",
      address: "Rod. Amaral Peixoto, n° 144 - KM 71 - Bacaxá, Saquarema / RJ",
      state: "RJ",
      latitude: -22.88851,
      longitude: -42.46728,
      zoom: 14,
      website: "https://instagram.com/retoquetintas",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "SB RIO",
      phone: "(21) 2424-5696",
      address:
        "Estr. do Gabinal, 1521 - Freguesia de Jacarepaguá, Rio de Janeiro / RJ",
      state: "RJ",
      latitude: -22.95203,
      longitude: -43.35057,
      zoom: 14,
      website: "https://www.sbrio.com/",
      product_line: [DistributorProductLine.LOTUS],
      country: "br",
    },
  ],
  "RN": [
    {
      name: "CS DISTRIBUIDORA",
      phone: "(84) 98153-6899",
      address:
        "Rua Lídia Ferreira De Souza, 09CS-C - Nova Esperança - Parnamirim - RN",
      state: "RN",
      latitude: -5.93614,
      longitude: -35.27701,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "RS": [
    {
      name: "Casa do Lavador UN. Gravataí",
      phone: "(51)3128-0500",
      address:
        " Av. Dorival Cândido Luz de Oliveira, 6735 - Bom Princípio, Gravataí - RS",
      state: "RS",
      latitude: -29.9321103,
      longitude: -51.0645935,
      zoom: 14,
      website: "https://www.casadolavador.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "Casa do Lavador UN. Osório",
      phone: "(51)99887-1744",
      address: " R. Costa Gama, 915 - Centro, Osório - RS",
      state: "RS",
      latitude: -29.8944676,
      longitude: -50.268441,
      zoom: 14,
      website: "https://www.casadolavador.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "Casa do Lavador UN. Porto Alegre I",
      phone: "(51)3207-8541",
      address: "Rua Cerro Azul, 646 - Santa Maria Goretti, Porto Alegre - RS",
      state: "RS",
      latitude: -30.0046797,
      longitude: -51.180852,
      zoom: 14,
      website: "https://www.casadolavador.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "Casa do Lavador UN. Porto Alegre II",
      phone: "(51)3737-4300",
      address:
        " Av. Bento Gonçalves, 8781 - loja 10 - São José, Porto Alegre - RS",
      state: "RS",
      latitude: -30.0767603,
      longitude: -51.133106,
      zoom: 14,
      website: "https://www.casadolavador.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "Casa do Lavador UN. Porto Alegre III",
      phone: "(51)99763-5649",
      address: "Av. Edgar Píres de Castro, 503 - Hípica, Porto Alegre - RS",
      state: "RS",
      latitude: -30.1565874,
      longitude: -51.1882189,
      zoom: 14,
      website: "https://www.casadolavador.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
  ],
  "SC": [
    {
      name: "LOJA VERDE CAR",
      phone: "(48) 99166-1521",
      address: "Av. Brg. da Silva Paes, 02 - Campinas, São José / SC",
      state: "SC",
      latitude: -28.6845,
      longitude: -49.33872,
      zoom: 14,
      product_line: [DistributorProductLine.LOTUS],
      country: "br",
    },
    {
      name: "M&M PRODUTOS DE LIMPEZA",
      phone: "(48) 99671-5768",
      address:
        "Av. Renato Ramos da Silva, 2781 - Vila Santo Antonio, Imbituba - SC, 88780-000",
      state: "SC",
      latitude: -28.26114,
      longitude: -48.68899,
      zoom: 14,
      website: "https://www.instagram.com/mmimbprodutosdelimpeza/",
      country: "br",
      product_line: [DistributorProductLine.LIMPOO],
    },
    {
      name: "SEMPRE LIMPO",
      phone: "(47) 97750527",
      address: "R. José Roberto Otto, 766, Porto Belo - SC, 88210-000",
      state: "SC",
      latitude: -27.15204,
      longitude: -48.58761,
      zoom: 14,
      country: "br",
      website: "https://www.instagram.com/smplimpo",
      product_line: [DistributorProductLine.LIMPOO],
    },
    {
      name: "SHOWCAR",
      phone: "(48) 99147-9468",
      address: "R. Acre, 525 - Nossa Sra. da Salete, Criciúma / SC",
      state: "SC",
      latitude: -28.6845,
      longitude: -49.33872,
      zoom: 14,
      website: "https://showcar.net.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "TEKPEL",
      phone: "(48) 99670-3322",
      address: "R. Osni João Vieira, 499 - Campinas, São José - SC, 88101-270",
      state: "SC",
      latitude: -27.59334,
      longitude: -48.61194,
      zoom: 14,
      website: "https://www.tekpel.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "SE": [
    {
      name: "Loja Super Brilho",
      phone: "(79)99681-6592",
      address: " Rua Acre, 819 - Siqueira CamposAracaju - SE",
      state: "SE",
      latitude: -10.9113614,
      longitude: -37.073372,
      zoom: 14,
      website: "",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
  "SP": [
    {
      name: "CASTORES PRODUTOS AUTOMOTIVOS",
      phone: "(11) 2598-8822",
      address:
        "Av senador Vergueiro, 3176 bairro Anchieta - São Bernardo do campo - SP",
      state: "SP",
      latitude: -23.6677741,
      longitude: -46.5628672,
      zoom: 14,
      website: "https://www.castores.com.br",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "D'ARTIBALE DECOR",
      phone: "(19) 3461-6314",
      address: "R. São Marcos, 39 - São Manoel, Americana - SP, 13472-200",
      state: "SP",
      latitude: -22.72831,
      longitude: -47.31455,
      zoom: 14,
      country: "br",
      website: "https://dartibaledecor.com.br/",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "EVO PRODUTOS",
      phone: "(19) 99925-6548",
      address: "Av. Eng. Antônio Francisco de Paula Souza, 3413 - Jardim São Vicente, Campinas - SP, 13045-137",
      state: "SP",
      latitude: -22.9341,
      longitude: -47.0853,
      zoom: 14,
      website: "https://www.evoprodutosautomotivos.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "GLOBAL DISTRIBUIDORA",
      phone: "(13) 97419-9299",
      address: "R. Emílio de Menezes, 717 - Cidade Ocian, Praia Grande - SP, 11704-170",
      state: "SP",
      latitude: -24.019,
      longitude: -46.414,
      zoom: 14,
      website: "https://www.instagram.com/globaldistribuidora.pg/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "JRCLEAN HIGIENIZAÇÕES",
      phone: "(11) 94725-3479",
      address:
        "Rua Angela Zampol N 234 - Bairro Suissa - Ribeirão Pires - SP, 09424-270",
      state: "SP",
      latitude: -23.714672,
      longitude: -46.422486,
      zoom: 14,
      country: "br",
      website: "https://www.jrcleanhigienizacoes.com",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "KUCHAR",
      phone: "(11) 5523-6364",
      address: "Av. Washington Luís, 714 - Santo Amaro, São Paulo - SP",
      state: "SP",
      latitude: -23.66035,
      longitude: -46.70345,
      zoom: 14,
      country: "br",
      website: "https://www.kuchar.com.br/",
      product_line: [DistributorProductLine.LOTUS, DistributorProductLine.LIMPOO],
    },
    {
      name: "LOJA DO PROFISSIONAL",
      address: "Rua Guaicurus, 101 - Água Branca - São Paulo / SP",
      phone: "(11) 3863-7200",
      website: "https://www.lojadoprofissional.com.br/",
      state: "SP",
      latitude: -23.52348,
      longitude: -46.68671,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "LOJA NEWS CAR",
      phone: "(11) 94006-4348",
      address: "R. Serra de Santa Marta, 158 - Vila Carmosina, São Paulo - SP, 08290-420",
      state: "SP",
      latitude: -23.556,
      longitude: -46.454,
      zoom: 14,
      website: "https://www.instagram.com/lojanewscar/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "Masterlimp Loja 1",
      phone: "(12)99130-6667",
      address: "Rua Olinda, N° 834 - Parque Industrial - São José dos Campos - SP, 12235-830",
      state: "SP",
      latitude: -23.2471248,
      longitude: -45.9132807,
      zoom: 14,
      website: "https://www.lojamasterlimp.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "Masterlimp Loja 2",
      phone: "(12)99130-6667",
      address: "Av. Andrômeda, N° 1610 - Jd Satélite, São José dos Campos - SP, 12235-830",
      state: "SP",
      latitude: -23.2268851,
      longitude: -45.8876892,
      zoom: 14,
      website: "https://www.lojamasterlimp.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "MENDES AUTO",
      phone: "(18)3907-7973",
      address:
        "Av Juscelino Kubitscheck de Oliveira, 2309 - Jardim everest - Presidente Prudente - SP",
      state: "SP",
      latitude: -22.105361,
      longitude: -51.4357949,
      zoom: 14,
      website: "https://www.mendesauto.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "NEXXUS CAR CARE",
      phone: "(11) 99009-3917",
      address: "Av. João Pedro Cardoso, 538 - Jabaquara, São Paulo - SP, 04355-001",
      state: "SP",
      latitude: -23.645,
      longitude: -46.645,
      zoom: 14,
      website: "https://www.nexxuscarcare.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "POLIVITRI COMÉRCIO DE PRODUTOS AUTOMOTIVOS LTDA",
      phone: "(11) 95458-0705",
      address: "Estrada Velha de Itapevi, 3068, Loja 5 - Barueri - SP, 06444-000",
      state: "SP",
      latitude: -23.489,
      longitude: -46.935,
      zoom: 14,
      website: "https://www.instagram.com/polivitri/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "Powerlimp Sorocaba",
      phone: "(15)3222-9880/(15)98145-9729",
      address: "R. Imperatriz Leopoldina, 822 - Vila Jardini, Sorocaba - SP, 18044-010",
      state: "SP",
      latitude: -23.5051321,
      longitude: -47.4820169,
      zoom: 14,
      website: "https://www.powerlimp.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "PROVALE AUTO CARE",
      phone: "(12) 3018-1700",
      address:
        "Av. Andrômeda, 3540 - Bosque dos Eucaliptos, São José dos Campos - SP",
      state: "SP",
      latitude: -23.243594,
      longitude: -45.885466,
      zoom: 14,
      website: "https://provale.net.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "QUICK CLEAN",
      address: "Av. Suplicy, 238 - Jd. Santa Mena - Guarulhos - SP",
      phone: "(11) 2414-4145",
      website: "https://www.quickclean.com.br/",
      state: "SP",
      latitude: -23.4505016,
      longitude: -46.5412414,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "STL / PRODUTOS DE LIMPEZA",
      phone: "(11) 26598026",
      address:
        "Av. Min. Laudo Ferreira de Camargo, 327 - Jardim Peri Peri, São Paulo - SP, 05537-001",
      state: "SP",
      latitude: -23.58696,
      longitude: -46.73708,
      zoom: 14,
      country: "br",
      website: "https://stldistribuidora.lojaintegrada.com.br/",
      product_line: [DistributorProductLine.LIMPOO],
    },
    {
      name: "VEGACLEAN",
      phone: "(11) 5560-3466 / (11) 94011-6846",
      address: "Rua Paulino Alves Escudeiro, 04B e 19 - Vila Guacuri, São Paulo - SP",
      state: "SP",
      latitude: -23.653,
      longitude: -46.642,
      zoom: 14,
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "VM AUTOCLEAN",
      phone: "(11) 94232-0372",
      address: "Av. Dos Latinos, 647 B, Jardim Santa Terezinha, São Paulo - SP",
      state: "SP",
      latitude: -23.57292,
      longitude: -46.4981,
      zoom: 14,
      country: "br",
      website: "https://www.vmautoclean.com.br",
      product_line: [DistributorProductLine.LOTUS],
    },
    {
      name: "WCF DISTRIBUIDORA",
      phone: "(17) 3224-4488",
      address: "Rua Coutinho Cavalcante, 846 - Jardim Alto Alegre, São José do Rio Preto - SP, 15054-300",
      state: "SP",
      latitude: -20.782,
      longitude: -49.37,
      zoom: 14,
      website: "https://www.wcfdistribuidora.com.br/",
      country: "br",
      product_line: [DistributorProductLine.LOTUS],
    },
  ],
};

export const DISTRIBUTORS_ITEMS: Array<Distributor> = Object.entries(
  DISTRIBUTORS_BY_STATE,
)
  .sort(([stateA], [stateB]) => stateA.localeCompare(stateB, "pt-BR"))
  .flatMap(([, distributors]) =>
    [...distributors].sort((distributorA, distributorB) =>
      distributorA.name.localeCompare(distributorB.name, "pt-BR"),
    ),
  )
  .map((distributor, index) => ({
    ...distributor,
    id: index + 1,
  }));
