on:
  push:
    branches:
      - develop
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.10.0

      - name: 🔨 Build Project
        env:
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID }}
          NEXT_SHARP_PATH: ${{ secrets.NEXT_SHARP_PATH }}
        run: |
          npm ci
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/www/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .env.example
            **/components/**
            **/context/**
            **/hooks/**
            **/libs/**
            **/pages/**
            .editorconfig
            .eslintrc.json
            .gitignore
            .prettierignore
            next-env.d.ts
            next-sitemap.config.js
            next.config.js
            README.md
            tsconfig.json
